### ISSUE TITLE
[General Question] Need help container installation

### ISSUE THREAD

**Issue by necrooo14** [jammsen/docker-palworld-dedicated-server#164] opened 2024-02-01 23:22 UTC
### Have you read the Important information text above

- [X] Yes i did

### Describe the feature

Hello 

 i am not so good with docker and need a bit help.
In Volume Configuration i set the volume but what i need to type in mount path.
Also i dont find any data in the directory from the server :/

### Additional information

- [ ] Would you be willing to help implement this feature?

### Final checks

- [X] I understand that this is a feature request function. I also unterstand that if i use this to report a bug report, that my issue might be un-answered closed.

**Comment by exovdo** [comment] 2024-02-02 01:05
I am going to assume the "volume" you're talking about is the "volumes:" section in the compose file?

If so, there are two terms that are important to learn: "absolute" path and "relative" path. "Absolute" means the entire path, while "relative" means the directory you're currently in.

So if I tell you to go to your Downloads folder in Windows, you can see it in two ways:

Absolute: C:\Users\$USERNAME\Downloads\

However if you're _already_ in your user folder, your relative path would be ".\Downloads\", with the ".\" denoting the directory you're currently in.

In Linux the exact same thing applies(though the ".\" is reversed the other way in Linux to be "./"). So in the compose file, the section with volumes shows as an example:

>     volumes:
>       - ./game:/palworld

What this tells docker compose to do is to use the current directory's "game" folder(this is what "./" is used for) and install the "palworld" folder inside the game folder.

So if you ran the compose file in "/srv/palworld/", the compose file would look for a "game" folder inside of there to then install Palworld into, which would look like this directory path: "/srv/palworld/game/"

If you saved and ran the compose file in the root user's home folder or a different user's home folder, those paths would look like:

> /root/game/
> /home/$USER/game/

So you'll need to see where you saved your compose file, and if you have created the appropriate "game" folder with permissions so the compose file can go into the "game" folder and install palworld.

Let me know if you need anything else clarified or if I got something wrong with understanding your post.

**Comment by necrooo14** [comment] 2024-02-02 11:09
Yeah i try this later when i am Home.
If i dont get IT worked would you be Up for 5or 10€ to make IT for me via Teamviewer?

**Comment by necrooo14** [comment] 2024-02-02 15:57
get still not working on saving files in directory i put know the windows game the folder. And i changed the first Volume but to /palworld but beside it he dont except ./Pal Server/game. 
Added some screenshots to
![Screenshot 2024-02-02 165324](https://github.com/jammsen/docker-palworld-dedicated-server/assets/158526743/ca707aab-83e4-4113-8a4b-3a24b48b4e3d)
![Screenshot 2024-02-02 165256](https://github.com/jammsen/docker-palworld-dedicated-server/assets/158526743/b02be43f-99ba-4cf1-b10f-de72acfc29fe)

**Comment by exovdo** [comment] 2024-02-02 16:55
Sure, I can help, add me on Discord or Steam:

Discord: echondo

Steam: https://steamcommunity.com/id/EChondo/

**Comment by jammsen** [comment] 2024-02-03 11:59
Hey @necrooo14 
You are missing the basic understanding of things, you need to want to learn that to fully understand what we are doing here. Paying someone to do something for 5 or 5000$ doesnt help you at all, because you dont understand what that person is doing.

I would recommend you to watch this "Docker-Tutorial" from KodeKloud, its from "Mumshad Mannambeth" he is awesome at teaching things and a well know ressource for good and understandable video guides. He has millions of views on YT and Udemy combined and every new developer watches his Docker course at my company and the feedback is always fantasic. Udemy-Course-Link: https://www.udemy.com/course/learn-docker/

If you dont want to pay money, you can watch a 2h version thats at bit older on YT:
https://www.youtube.com/watch?v=zJ6WbK9zFpI

**Comment by jammsen** [comment] 2024-02-03 12:00
Also @necrooo14 you are always welcome in the Discord to ask questions like theese, you dont need to pay money for that. If someone asks you to pay money for this let me know and i will deal with that ... thats a no-go! I wont tolerate that!

**Comment by necrooo14** [comment] 2024-02-03 18:35
I tried it 6 hours and exovdo tried it  2hours via teamviewer and didnt get it worket too, but we had some nice time and talking about lots of things he live in the USA I in Germany was very nice. I dont want to spend more time  on it now. I wait a year maybe then it worked better when the game is not in early access :) 
But thank you all for your help.

PS: He didnt wanted any Money from me. I wanted to pay him because he worked 2 hours for me but he dont accept it :)

**Comment by jammsen** [comment] 2024-02-03 19:33
@necrooo14 Im guessing you are using some kind of NAS like QNAP or Synology? If yes, look at the closed issues and join the Discord there are people that can help.

**Comment by OnkelT** [comment] 2024-02-03 19:40
@necrooo14 I don't know if the Problem is sovled but if you need help to setup you're server I would try to help. I read that you're from Germany if you wish we could speak in German. I'm a "Azubi Fachinformatiker für Systemintegration" from Germany ;) 

Back to topic: 
The Problem you're facing sound exactly like the problem I faced 2 days ago. LSS: My Server is running with my old save files from my steam dedicated server. I figured out myself how to solve anything, to get it running, took me 2 days. 

So if you want to know more how I solved everything, add me on Discord: thetazzy

**Comment by jammsen** [comment] 2024-02-05 12:48
Im closing this issue as resolved, feel free to reach out again in the Discord and ask questions, if you need help.

If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.

**Closed by jammsen** 2024-02-05 12:48 UTC
Labels: question, inacticity-close
