### ISSUE TITLE
[Bug Report] Palworld server exits while container install

### ISSUE THREAD

**Issue by DarthSett** [jammsen/docker-palworld-dedicated-server#163] opened 2024-02-01 16:45 UTC
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When I run "docker-compose up", after a while, the container exits and restarts

### Desired behavior

the container doesn't exit

### Links to screenshots

No screenshot but here are the logs (at least towards the end where everything started going bad):

 Update state (0x81) verifying update, progress: 61.15 (1382151677 / 2260207317)
palworld-dedicated-server  |  Update state (0x81) verifying update, progress: 87.57 (1979375173 / 2260207317)
palworld-dedicated-server  | Success! App '2394010' fully installed.
palworld-dedicated-server  | >>> Doing an update and validate of the gameserver files
palworld-dedicated-server  | tid(94) burning pthread_key_t == 0 so we never use it
palworld-dedicated-server  | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
palworld-dedicated-server  | Logging directory: '/home/steam/Steam/logs'
palworld-dedicated-server  | [  0%] Checking for available updates...
palworld-dedicated-server  | [----] Verifying installation...
palworld-dedicated-server  | Steam Console Client (c) Valve Corporation - version 1705108307
palworld-dedicated-server  | -- type 'quit' to exit --
palworld-dedicated-server  | Loading Steam API...OK
palworld-dedicated-server  |
palworld-dedicated-server  | Connecting anonymously to Steam Public...OK
palworld-dedicated-server  | Waiting for client config...OK
palworld-dedicated-server  | Waiting for user info...OK
palworld-dedicated-server  |  Update state (0x5) verifying install, progress: 0.32 (7340032 / 2260207317)
palworld-dedicated-server  |  Update state (0x5) verifying install, progress: 16.18 (365611604 / 2260207317)
palworld-dedicated-server  |  Update state (0x5) verifying install, progress: 41.43 (936390301 / 2260207317)
palworld-dedicated-server  |  Update state (0x5) verifying install, progress: 66.97 (1513715505 / 2260207317)
palworld-dedicated-server  |  Update state (0x5) verifying install, progress: 90.83 (2052919961 / 2260207317)
palworld-dedicated-server  | Success! App '2394010' fully installed.
palworld-dedicated-server  | >>> Starting the gameserver
palworld-dedicated-server  | >>> Setting up Engine.ini ...
palworld-dedicated-server  | > SERVER_SETTINGS_MODE is set to manual, NOT using environment variables to configure the server!
palworld-dedicated-server  | > File /palworld/Pal/Saved/Config/LinuxServer/Engine.ini has to be manually set by user
palworld-dedicated-server  | >>> Finished setting up Engine.ini ...
palworld-dedicated-server  | >>> Setting up PalWorldSettings.ini ...
palworld-dedicated-server  | > Checking if config already exists
palworld-dedicated-server  | > No config found, generating one
palworld-dedicated-server  | mkdir: cannot create directory '/palworld/Pal': Operation not permitted
palworld-dedicated-server  | cp: cannot stat '/palworld/DefaultPalWorldSettings.ini': No such file or directory
palworld-dedicated-server  | > SERVER_SETTINGS_MODE is set to manual, NOT using environment variables to configure the server!
palworld-dedicated-server  | > File /palworld/Pal/Saved/Config/LinuxServer/PalWorldSettings.ini has to be manually set by user
palworld-dedicated-server  | >>> Finished setting up PalWorldSettings.ini ...
palworld-dedicated-server  | > Setting Community-Mode to enabled
palworld-dedicated-server  | > Setting Multi-Core-Enchancements to enabled
palworld-dedicated-server  | /servermanager.sh: line 36: ./PalServer.sh: No such file or directory
palworld-dedicated-server exited with code 0

### To Reproduce

nada

### Software setup

- OS: macOs Monterey

### Hardware setup

 nada

### Additional context

here is my env file:
# Change this for logging and backup, see "Environment variables" in the README.md
TZ=Asia/Kolkata
ALWAYS_UPDATE_ON_START=true
MULTITHREAD_ENABLED=true
COMMUNITY_SERVER=true
BACKUP_ENABLED=true
BACKUP_CRON_EXPRESSION=0 * * * *
BACKUP_RETENTION_POLICY=true
BACKUP_RETENTION_AMOUNT_TO_KEEP=30
STEAMCMD_VALIDATE_FILES=true
# Change this to manual if you want to edit your configs yourself
SERVER_SETTINGS_MODE=manual 
WEBHOOK_ENABLED=false
WEBHOOK_URL="YOUR-URL-IN-HERE"
WEBHOOK_START_TITLE="Server is starting"
WEBHOOK_START_DESCRIPTION="The gameserver is starting"
WEBHOOK_START_COLOR="2328576"
WEBHOOK_STOP_TITLE="Server has been stopped"
WEBHOOK_STOP_DESCRIPTION="The gameserver has been stopped"
WEBHOOK_STOP_COLOR="7413016"
WEBHOOK_INFO_TITLE="Info"
WEBHOOK_INFO_DESCRIPTION="This is an info from the server"
WEBHOOK_INFO_COLOR="2849520"
NETSERVERMAXTICKRATE=120
DIFFICULTY=Normal
DAYTIME_SPEEDRATE=1.000000
NIGHTTIME_SPEEDRATE=1.000000
EXP_RATE=2.000000
PAL_CAPTURE_RATE=1.000000
PAL_SPAWN_NUM_RATE=1.000000
PAL_DAMAGE_RATE_ATTACK=1.000000
PAL_DAMAGE_RATE_DEFENSE=1.000000
PLAYER_DAMAGE_RATE_ATTACK=1.000000
PLAYER_DAMAGE_RATE_DEFENSE=1.000000
PLAYER_STOMACH_DECREASE_RATE=1.000000
PLAYER_STAMINA_DECREACE_RATE=1.000000
PLAYER_AUTO_HP_REGENE_RATE=2.000000
PLAYER_AUTO_HP_REGENE_RATE_IN_SLEEP=4.000000
PAL_STOMACH_DECREACE_RATE=1.000000
PAL_STAMINA_DECREACE_RATE=1.000000
PAL_AUTO_HP_REGENE_RATE=1.000000
PAL_AUTO_HP_REGENE_RATE_IN_SLEEP=1.000000
BUILD_OBJECT_DAMAGE_RATE=1.000000
BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=1.000000
COLLECTION_DROP_RATE=1.000000
COLLECTION_OBJECT_HP_RATE=1.000000
COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1.000000
ENEMY_DROP_ITEM_RATE=4.000000
DEATH_PENALTY=Item
ENABLE_PLAYER_TO_PLAYER_DAMAGE=false
ENABLE_FRIENDLY_FIRE=false
ENABLE_INVADER_ENEMY=true
ACTIVE_UNKO=false
ENABLE_AIM_ASSIST_PAD=true
ENABLE_AIM_ASSIST_KEYBOARD=false
DROP_ITEM_MAX_NUM=3000
DROP_ITEM_MAX_NUM_UNKO=100
BASE_CAMP_MAX_NUM=128
BASE_CAMP_WORKER_MAXNUM=15
DROP_ITEM_ALIVE_MAX_HOURS=1.000000
AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=false
AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.000000
GUILD_PLAYER_MAX_NUM=20
PAL_EGG_DEFAULT_HATCHING_TIME=72.000000
WORK_SPEED_RATE=2.000000
IS_MULTIPLAY=true
IS_PVP=false
CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=false
ENABLE_NON_LOGIN_PENALTY=false
ENABLE_FAST_TRAVEL=true
IS_START_LOCATION_SELECT_BY_MAP=true
EXIST_PLAYER_AFTER_LOGOUT=true
ENABLE_DEFENSE_OTHER_GUILD_PLAYER=false
COOP_PLAYER_MAX_NUM=4
MAX_PLAYERS=32
SERVER_NAME=Tequila-Sunsett
SERVER_DESCRIPTION=Palworld-Dedicated-Server running in Docker hosted by Tequila Sunsett
ADMIN_PASSWORD=adminPassword
SERVER_PASSWORD=darthsett
PUBLIC_PORT=8211
PUBLIC_IP=<my public ip>
RCON_ENABLED=true
RCON_PORT=25575
REGION=
USEAUTH=true
BAN_LIST_URL=https://api.palworldgame.com/api/banlist.txt

**Comment by DarthSett** [comment] 2024-02-01 17:37
My bad
I forgot to chmod 777 game
But now my server isn't showing up on community servers list. My logs are giving some   S_API Fails at the end now

**Comment by thejcpalma** [comment] 2024-02-01 20:27
@DarthSett No worries. Next time, read the README.md carefully 😊
Also, read the FAQs, has your answer 😉

Close this issue after 😎

**Comment by DarthSett** [comment] 2024-02-02 05:11
@thejcpalma Ok. I get that the errors are safe to ignore. But my server still doesn't show up on the community server list.

**Comment by DarthSett** [comment] 2024-02-02 09:57
I'm also not able to enter the server using direct connect

**Comment by thejcpalma** [comment] 2024-02-02 10:40
> @thejcpalma Ok. I get that the errors are safe to ignore. But my server still doesn't show up on the community server list.

Server list search is a known bug, use direct connect, and it will show up on recent servers later

> I'm also not able to enter the server using direct connect

This is because you're using public IP for connecting (confirmed via discord) and your port forwarding is not done correctly, so you are able to join when in the same network with local IP but using public IP won't work.

**Comment by jammsen** [comment] 2024-02-03 11:40
Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [docker-hub-repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.

**Closed by jammsen** 2024-02-03 11:40 UTC
Labels: not-a-bug, possible-config-error, possible-provision-error
