### ISSUE TITLE
Rcon.yaml Placement

### ISSUE THREAD

**Issue by wwalker0307** [jammsen/docker-palworld-dedicated-server#199] opened 2024-02-14 07:41 UTC
### Have you read the Important information text above

- [X] Yes i did

### Current behavior

When attempting to execute an RCON command, it fails with 'unknown port'
```
docker exec Palworld rconcli showplayers
cli: execute: auth: rcon: dial tcp: address tcp/###RCON_PORT###: unknown port
> RCON:

```
Where should the rcon.yaml file be placed?

### Desired behavior

RCON works.

### To Reproduce

docker exec Palworld rconcli showplayers

### Software setup

- OS: Ubuntu 22.04
- Docker: 25.0.2

### Hardware setup

- vCPU: 8
- RAM: 32GB
- Disk: 100GB

**Comment by jammsen** [comment] 2024-02-14 13:29
Hey @wwalker0307 - Sorry but the fields `Additional context` and `To Reproduce` are there to help me to understand your problem .... But i dont right now ... Because als you did was give me an error. No information on your settings (docker-compose.yml/default.env) listed, no information when you last upgraded your image, no info what SETTINGS_MODE you using, no nothing ... Seriously im not trying to be mean here, but how do you expect me to be of any help to you?! In an abstract way you said "The white wall looks weird" thats it, no context. ❓ ❔ Help me to help you please!

**Comment by MiX74P3** [comment] 2024-02-14 21:11
Is this this same type of issue? I woke up today w server not responding. stopped server and tried bring it it back up to find this issue. How can I fix this?


mix74p3@mix74p3:~/docker-palworld-dedicated-server$ docker compose up -d
[+] Running 1/0
 ✔ Container palworld-dedicated-server  Started
mix74p3@mix74p3:~/docker-palworld-dedicated-server$ docker compose logs -f
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
palworld-dedicated-server  | > Current steam user PUID is '1000' and PGID is '1000'
palworld-dedicated-server  | > PUID and PGID matching what is requested for user steam
palworld-dedicated-server  | chown: changing ownership of '/home/steam/steamcmd/rcon.yaml': Operation not permitted
mix74p3@mix74p3:~/docker-palworld-dedicated-server$

**Comment by wwalker0307** [comment] 2024-02-14 21:20
> Hey @wwalker0307 - Sorry but the fields `Additional context` and `To Reproduce` are there to help me to understand your problem .... But i dont right now ... Because als you did was give me an error. No information on your settings (docker-compose.yml/default.env) listed, no information when you last upgraded your image, no info what SETTINGS_MODE you using, no nothing ... Seriously im not trying to be mean here, but how do you expect me to be of any help to you?! In an abstract way you said "The white wall looks weird" thats it, no context. ❓ ❔ Help me to help you please!

Just under the error information I was asking where the rcon.yaml file should be in the file system.  However, since then I noticed the environment variable where it specifies that file location and adjusted accordingly.  For my "problem" this issue can be closed.

**Comment by jammsen** [comment] 2024-02-14 23:26
@MiX74P3 

> Is this this same type of issue? I woke up today w server not responding. stopped server and tried bring it it back up to find this issue. How can I fix this?

Update your install to the newest version, a lot has changed, if you still have a problem, please open an own issue.

@wwalker0307 - Glad to hear it works

Im closing this issue as resolved, feel free to reach out again if you need help.

If you like this project, please consider giving this repo and the [Docker-Hub-Repo](https://hub.docker.com/repository/docker/jammsen/palworld-dedicated-server) a Star.

**Closed by jammsen** 2024-02-14 23:26 UTC
Labels: issue-inconclusive, issue-unclear, waiting-for-feedback, needs-more-information
